In [78]:
import json
from numpy.random import choice

In [79]:
ori_ipynb = json.load(open('final-exam.ipynb', encoding = "utf-8"))
cells = ori_ipynb['cells']

a_bucket = {}
b_bucket = {}
c_bucket = {}
d_bucket = {}
ai = bi = ci = di = 1
for i, cell in enumerate(cells):
    if cell['source'][0][:2] == "##":
        if cell['source'][0][4] == 'a':
            a_bucket[ai] = [cells[i], cells[i+1]]
            ai += 1
        if cell['source'][0][4] == 'b':
            b_bucket[bi] = [cells[i], cells[i+1]]
            bi += 1
        if cell['source'][0][4] == 'c':
            c_bucket[ci] = [cells[i], cells[i+1]]
            ci += 1
        if cell['source'][0][4] == 'd':
            d_bucket[di] = [cells[i], cells[i+1]]
            di += 1

In [88]:
with open('id.txt') as f:
    ids = f.read().split('\n')

In [89]:
for stu_id in ids:
    output_ipynb_file = dict(ori_ipynb)
    del output_ipynb_file['cells']

    a_select = choice(range(1, len(a_bucket)+1), 3, replace = False)
    a_select.sort()
    b_select = choice(range(1, len(b_bucket)+1), 2, replace = False)
    b_select.sort()
    c_select = choice(range(1, len(c_bucket)+1), 1, replace = False)
    c_select.sort()
    d_select = choice(range(1, len(d_bucket)+1), 1, replace = False)
    d_select.sort()
    print(a_select)
    print(b_select)
    print(c_select)
    print(d_select)

    output_cells = []
    for a in a_select:
        output_cells += a_bucket[a]
    for b in b_select:
        output_cells += b_bucket[b]
    for c in c_select:
        output_cells += c_bucket[c]
    for d in d_select:
        output_cells += d_bucket[d]

    output_ipynb_file['cells'] = output_cells

    json.dump(output_ipynb_file, open(f'Test Papers/{stu_id}.ipynb', 'w'))

[1 4 5]
[2 3]
[2]
[2]
[4 5 6]
[1 4]
[3]
[2]
[3 4 6]
[1 2]
[3]
[2]
[3 4 5]
[3 4]
[1]
[1]
[3 4 6]
[1 4]
[1]
[3]
[2 3 4]
[2 3]
[1]
[2]
[2 5 6]
[1 4]
[2]
[2]
[1 2 5]
[2 4]
[3]
[2]
[2 3 5]
[1 2]
[3]
[3]
[1 4 5]
[1 4]
[1]
[3]
[2 3 4]
[2 4]
[1]
[1]
[1 3 4]
[3 4]
[1]
[1]
[2 3 6]
[1 3]
[1]
[1]
[2 4 5]
[1 3]
[1]
[2]
[1 2 6]
[2 3]
[3]
[2]
[3 4 5]
[3 4]
[3]
[3]
[4 5 6]
[1 2]
[3]
[2]
[2 4 5]
[1 2]
[3]
[1]
[1 4 5]
[1 4]
[1]
[1]
[1 4 5]
[1 3]
[2]
[3]
[1 2 6]
[2 3]
[3]
[2]
[2 3 6]
[3 4]
[3]
[2]
[4 5 6]
[3 4]
[2]
[1]
[1 2 6]
[1 2]
[2]
[1]
[3 5 6]
[1 2]
[3]
[1]
[3 5 6]
[3 4]
[1]
[3]
[2 4 5]
[2 4]
[1]
[2]
[1 4 6]
[2 3]
[1]
[3]
[4 5 6]
[2 4]
[1]
[3]
[4 5 6]
[1 2]
[2]
[2]
[1 2 5]
[2 4]
[2]
[3]
[2 4 6]
[2 3]
[3]
[1]
[2 4 6]
[2 3]
[1]
[1]
[3 5 6]
[3 4]
[1]
[3]
[1 4 6]
[2 3]
[1]
[3]
[2 3 5]
[2 4]
[3]
[3]
[1 3 4]
[1 4]
[3]
[2]
[3 4 6]
[2 3]
[2]
[2]
[2 3 5]
[1 4]
[3]
[2]
[3 5 6]
[3 4]
[1]
[3]
[1 3 4]
[1 3]
[3]
[1]
[2 4 6]
[2 4]
[2]
[3]
[3 5 6]
[1 2]
[1]
[2]
[2 3 5]
[3 4]
[1]
[3]
[4 5 6]
[2 4]
[3]
[1]
[1 4 5]
[2