In [2]:
import numpy as np # 通常會用 "np" 當作 numpy 的簡寫

### Numpy 內的容器 : `ndarray`

可以使用python內建的`list`或是`tuple`建立一個`ndarray`

In [5]:
mat = np.array([1, 2, 3, 4])
print(type(mat))
print(mat)

<class 'numpy.ndarray'>
[1 2 3 4]


### `ndarray`可以是一維、二維，甚至是多維度

In [9]:
mat = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(type(mat))
print(mat)

<class 'numpy.ndarray'>
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


### `numpy`建立等差數列(一維的`ndarray`)

* `np.arange([start, ]stop, [step, ]dtype=None)`

參數用法跟python內建的`range`很類似

* `np.arange(10)` = `np.arange(stop = 10)`
* `np.arange(3, 10)` = `np.arange(start = 3, stop = 10)`
* `np.arange(1, 9, 2)` = `np.arange(start = 1, stop = 9, step = 2)`

In [17]:
mat = np.arange(10)
print(mat)

[0 1 2 3 4 5 6 7 8 9]


In [18]:
mat = np.arange(3, 10)
print(mat)

[3 4 5 6 7 8 9]


In [19]:
mat = np.arange(1, 9, 2)
print(mat)

[1 3 5 7]


In [25]:
mat = np.arange(1, 3, 0.1) # step 參數可以使用小數
print(mat)

[1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9 2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7
 2.8 2.9]


### `ndarray`取值

跟`list`大同小異，但更有彈性

In [62]:
mat = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(mat)
print("-------------")
print(mat[1, 2]) # mat[行數, 列數]
print("-------------")
print(mat[0:2, 0:2]) # mat[行數開始:行數結束, 列數開始:列數結束]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
-------------
7
-------------
[[1 2]
 [5 6]]


In [64]:
mat = np.array([1, 2, 3, 5, 6, 7])
print(mat)
print("-------------")
print(mat[[1, 3, 5]]) # 可以取不連續的值，但記得要兩層中括號

[1 2 3 5 6 7]
-------------
[2 5 7]


### `ndarray`的運算

`ndarray` 可以使用 `+` `-` `*` `/` 等運算子，會直接對矩陣的每個資料做運算

In [75]:
mat = np.array([[1, 2, 3], [4, 5, 6]])
print(mat)

print("--------------")
mat2 = mat + 3
print(mat2)

[[1 2 3]
 [4 5 6]]
--------------
[[4 5 6]
 [7 8 9]]


In [76]:
mat = np.arange(1, 11)
print(mat)
mat2 = mat ** 3
print(mat2)

[ 1  2  3  4  5  6  7  8  9 10]
[   1    8   27   64  125  216  343  512  729 1000]


### `ndarray` 的串接

分成橫向跟綜向兩種

* np.hstack((mat1, mat2)) # 橫向串接，mat1、mat2是要串接的矩陣
* np.vstack((mat1, mat2)) # 縱向

In [83]:
mat1 = np.array([[1, 2], [3, 4]])
print(mat1)
print("---------------")
mat2 = np.array([[5, 6], [7, 8]])
print(mat2)
print("---------------")
mat3 = np.hstack((mat1, mat2))
print(mat3)

[[1 2]
 [3 4]]
---------------
[[5 6]
 [7 8]]
---------------
[[1 2 5 6]
 [3 4 7 8]]


In [84]:
mat1 = np.array([[1, 2], [3, 4]])
print(mat1)
print("---------------")
mat2 = np.array([[5, 6], [7, 8]])
print(mat2)
print("---------------")
mat3 = np.vstack((mat1, mat2))
print(mat3)

[[1 2]
 [3 4]]
---------------
[[5 6]
 [7 8]]
---------------
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


### `numpy` 三角函數

* `np.sin()`
* `np.cos()`
* `np.tan()`
* ...

中間的參數可以放一個數字，也可以放容器(`list` / `ndarray` / ...etc)

In [79]:
n = np.sin(2)
print(n)

0.9092974268256817


In [80]:
mat = np.arange(1, 11)
print(mat)
cos_mat = np.cos(mat)
print(cos_mat)

[ 1  2  3  4  5  6  7  8  9 10]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219  0.96017029
  0.75390225 -0.14550003 -0.91113026 -0.83907153]


### `ndarray` 常用的屬性(attr) :

* `.shape` : `tuple`，是這個`ndarray`每個維度的長度
* `.ndim` : `number`，這個`ndarray`是幾維
* `.size` : `number`，這個`ndarray`
* `.dtype` : 這個`ndarray`的資料型態(如int32就代表32位元的整數)
* `.T` : 轉置矩陣

In [15]:
mat = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(f"shape :", mat.shape)
print(f"ndim :", mat.ndim)
print(f"size :", mat.size)
print(f"dtype :", mat.dtype)
print(f"T :")
print(mat.T)

shape : (3, 4)
ndim : 2
size : 12
dtype : int32
T :
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


### 建立全零 or 全一矩陣

* `np.zeros((第一維長度, 第二維長度, 第三維長度 ...))` : 建立全零矩陣
* `np.ones((第一維長度, 第二維長度, 第三維長度 ...))` : 建立全一矩陣

In [28]:
mat = np.zeros((4, 2))
print(mat)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [29]:
mat = np.ones((2, 3))
print(mat)

[[1. 1. 1.]
 [1. 1. 1.]]


In [32]:
mat = np.ones((2, 3, 4))
print(mat)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


### 建立亂數矩陣

* `np.random.rand(第一維長度, 第二維長度, 第三維長度 ...)` : 亂數為0~1之間的隨機數。

* `np.random.randint(low, high=None, size=None, dtype="I")` : 亂數為參數`low`與`high`之間(不包含high)的隨機數，size=(第一維長度, 第二維長度, 第三維長度 ...)的`tuple`或`list`

其他各種隨機函數的使用方法可以參考 [官網doc](https://numpy.org/doc/stable/reference/random/index.html#module-numpy.random)

In [33]:
mat = np.random.rand(2, 3)
print(mat)

[[0.61894095 0.3643806  0.92775944]
 [0.46984165 0.28858064 0.02153575]]


In [35]:
# 也可以二維以上
mat = np.random.rand(2, 3, 4)
print(mat)

[[[0.33368849 0.81698102 0.65010829 0.25573587]
  [0.15516001 0.73852398 0.66195512 0.96195575]
  [0.96036806 0.26253016 0.00672796 0.94173966]]

 [[0.51582436 0.09886186 0.20438888 0.19654429]
  [0.8774055  0.19533403 0.82850219 0.38491874]
  [0.95909571 0.03991242 0.74376441 0.00200072]]]


In [38]:
mat = np.random.randint(1, 3, size = (3, 3))
print(mat)

[[2 1 2]
 [2 1 1]
 [2 1 2]]
